## Importing Libraries

In [1]:
import numpy as np
from numpy import genfromtxt

## Data Preperation

In [4]:
data = genfromtxt('DATA/bank_note_data.txt',delimiter=',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels = data[:,4]

In [7]:
features = data[:,0:4]

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
len(X_train)

919

In [12]:
len(X)

1372

## Normalization

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler()

In [15]:
X_train = scaler.fit_transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
X_train.max()

1.0000000000000002

## Neural Network

In [19]:
from keras.layers import Dense
from keras.models import Sequential

In [21]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [22]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [23]:
model.fit(X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6895 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6861 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6825 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6778 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6706 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6626 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6537 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6450 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6382 - acc: 0.5495
Epoch 10/50
 - 0s - loss: 0.6321 - acc: 0.6496
Epoch 11/50
 - 0s - loss: 0.6269 - acc: 0.6692
Epoch 12/50
 - 0s - loss: 0.6218 - acc: 0.6692
Epoch 13/50
 - 0s - loss: 0.6164 - acc: 0.6877
Epoch 14/50
 - 0s - loss: 0.6108 - acc: 0.6877
Epoch 15/50
 - 0s - loss: 0.6051 - acc: 0.6899
Epoch 16/50
 - 0s - loss: 0.5990 - acc: 0.6931
Epoch 17/50
 - 0s - loss: 0.5928 - acc: 0.6997
Epoch 18/50
 - 0s - loss: 0.5865 - acc: 0.6986
Epoch 19/50
 - 0s - loss: 0.5798 - acc: 0.7182
Epoch 20/50
 - 0s - loss: 0.5731 - acc: 0.7291
Epoch 21/50
 - 0s - loss: 0.5656 - acc: 0.7345
Epoch 22/50
 - 0s - lo

## Prediction

In [26]:
model.predict_classes(X_test)
print('reset')

reset


In [27]:
model.metrics_names

['loss', 'acc']

## Evaluation

In [29]:
from sklearn.metrics import confusion_matrix,classification_report

In [30]:
predictions = model.predict_classes(X_test)

In [31]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [ 26, 170]], dtype=int64)

In [32]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.91      0.99      0.95       257
        1.0       0.98      0.87      0.92       196

avg / total       0.94      0.94      0.94       453



## Saving Model

In [33]:
model.save('model_01_.h5')

## Loading Model

In [34]:
from keras.models import load_model

In [35]:
new_model = load_model('model_01_.h5')

In [36]:
new_model.predict_classes(X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
    