<a href="https://colab.research.google.com/github/euguroglu/Machine-Learning-Projects/blob/master/NLP_Pytorch_Shakespeare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
from torch import nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
with open('shakespeare.txt','r',encoding='utf8') as f:
  text = f.read()

In [23]:
type(text)

str

In [24]:
text[:1000]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bud buriest thy content,\n  And tender churl mak'st waste in niggarding:\n    Pity the world, or else this glutton be,\n    To eat the world's due, by the grave and thee.\n\n\n                     2\n  When forty winters shall besiege thy brow,\n  And dig deep trenches in thy beauty's field,\n  Thy youth's proud livery so gazed on now,\n  Will be a tattered weed of small worth held:  \n  Then being asked, where all thy beauty lies,\n  Where all the treasure of thy lusty days;\n  To sa

In [25]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [26]:
len(text)

5445609

In [27]:
all_characters = set(text)

In [28]:
all_characters

{'\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}'}

In [29]:
len(all_characters)

84

Decoder takes number and transform it into letter

In [30]:
decoder = dict(enumerate(all_characters))

In [31]:
decoder

{0: 'b',
 1: '9',
 2: 'w',
 3: '[',
 4: 'W',
 5: 'P',
 6: 'a',
 7: 'B',
 8: 'S',
 9: 'x',
 10: 'n',
 11: 'k',
 12: 'H',
 13: '!',
 14: 'C',
 15: 'K',
 16: 'r',
 17: '|',
 18: 'u',
 19: ':',
 20: 'J',
 21: 'j',
 22: '2',
 23: '7',
 24: 't',
 25: '&',
 26: 'd',
 27: '`',
 28: '8',
 29: ',',
 30: "'",
 31: '6',
 32: 'l',
 33: '.',
 34: '<',
 35: ']',
 36: ';',
 37: 'T',
 38: '3',
 39: '_',
 40: 'A',
 41: 'y',
 42: 'L',
 43: '5',
 44: 'V',
 45: 'e',
 46: 'Q',
 47: 'N',
 48: 'p',
 49: '4',
 50: 'z',
 51: '?',
 52: ' ',
 53: 'h',
 54: 'D',
 55: 'U',
 56: ')',
 57: 's',
 58: 'F',
 59: 'v',
 60: '(',
 61: '0',
 62: 'G',
 63: 'X',
 64: '>',
 65: 'c',
 66: 'Z',
 67: 'E',
 68: '}',
 69: 'i',
 70: 'R',
 71: 'M',
 72: 'I',
 73: '-',
 74: 'g',
 75: 'q',
 76: '"',
 77: '1',
 78: 'm',
 79: '\n',
 80: 'f',
 81: 'Y',
 82: 'O',
 83: 'o'}

In [32]:
encoder = {char: ind for ind,char in decoder.items()}

In [33]:
encoder

{'\n': 79,
 ' ': 52,
 '!': 13,
 '"': 76,
 '&': 25,
 "'": 30,
 '(': 60,
 ')': 56,
 ',': 29,
 '-': 73,
 '.': 33,
 '0': 61,
 '1': 77,
 '2': 22,
 '3': 38,
 '4': 49,
 '5': 43,
 '6': 31,
 '7': 23,
 '8': 28,
 '9': 1,
 ':': 19,
 ';': 36,
 '<': 34,
 '>': 64,
 '?': 51,
 'A': 40,
 'B': 7,
 'C': 14,
 'D': 54,
 'E': 67,
 'F': 58,
 'G': 62,
 'H': 12,
 'I': 72,
 'J': 20,
 'K': 15,
 'L': 42,
 'M': 71,
 'N': 47,
 'O': 82,
 'P': 5,
 'Q': 46,
 'R': 70,
 'S': 8,
 'T': 37,
 'U': 55,
 'V': 44,
 'W': 4,
 'X': 63,
 'Y': 81,
 'Z': 66,
 '[': 3,
 ']': 35,
 '_': 39,
 '`': 27,
 'a': 6,
 'b': 0,
 'c': 65,
 'd': 26,
 'e': 45,
 'f': 80,
 'g': 74,
 'h': 53,
 'i': 69,
 'j': 21,
 'k': 11,
 'l': 32,
 'm': 78,
 'n': 10,
 'o': 83,
 'p': 48,
 'q': 75,
 'r': 16,
 's': 57,
 't': 24,
 'u': 18,
 'v': 59,
 'w': 2,
 'x': 9,
 'y': 41,
 'z': 50,
 '|': 17,
 '}': 68}

In [34]:
encoded_text = np.array([encoder[char] for char in text])

In [35]:
encoded_text[:500]

array([79, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 77, 79, 52, 52, 58, 16, 83, 78, 52, 80,  6, 69,
       16, 45, 57, 24, 52, 65, 16, 45,  6, 24, 18, 16, 45, 57, 52,  2, 45,
       52, 26, 45, 57, 69, 16, 45, 52, 69, 10, 65, 16, 45,  6, 57, 45, 29,
       79, 52, 52, 37, 53,  6, 24, 52, 24, 53, 45, 16, 45,  0, 41, 52,  0,
       45,  6, 18, 24, 41, 30, 57, 52, 16, 83, 57, 45, 52, 78, 69, 74, 53,
       24, 52, 10, 45, 59, 45, 16, 52, 26, 69, 45, 29, 79, 52, 52,  7, 18,
       24, 52,  6, 57, 52, 24, 53, 45, 52, 16, 69, 48, 45, 16, 52, 57, 53,
       83, 18, 32, 26, 52,  0, 41, 52, 24, 69, 78, 45, 52, 26, 45, 65, 45,
        6, 57, 45, 29, 79, 52, 52, 12, 69, 57, 52, 24, 45, 10, 26, 45, 16,
       52, 53, 45, 69, 16, 52, 78, 69, 74, 53, 24, 52,  0, 45,  6, 16, 52,
       53, 69, 57, 52, 78, 45, 78, 83, 16, 41, 19, 79, 52, 52,  7, 18, 24,
       52, 24, 53, 83, 18, 52, 65, 83, 10, 24, 16,  6, 65, 24, 45, 26, 52,
       24, 83, 52, 24, 53

In [36]:
decoder[9] #space

'x'

In [37]:
def one_hot_encoder(encoded_text,num_uni_chars):

  # encoded text --> batch of encoded text
  # num_uni_chars --> len(set(text))

  one_hot = np.zeros((encoded_text.size,num_uni_chars))
  one_hot = one_hot.astype(np.float32)
  one_hot[np.arange(one_hot.shape[0]),encoded_text.flatten()] = 1.0
  one_hot = one_hot.reshape((*encoded_text.shape,num_uni_chars))

  return one_hot



In [38]:
one_hot_encoder(np.array([1,2,0]),3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [39]:
example_Text = np.arange(10)

In [40]:
example_Text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
example_Text.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
def generate_batches(encoded_text,samp_per_batch=10,seq_len=50):
    # Total number of characters per batch
    # Example: If samp_per_batch is 2 and seq_len is 50, then 100
    # characters come out per batch.
    char_per_batch = samp_per_batch * seq_len
    
    
    # Number of batches available to make
    # Use int() to roun to nearest integer
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # Cut off end of encoded_text that
    # won't fit evenly into a batch
    encoded_text = encoded_text[:num_batches_avail * char_per_batch]
    
    
    # Reshape text into rows the size of a batch
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    

    # Go through each row in array.
    for n in range(0, encoded_text.shape[1], seq_len):
        
        # Grab feature characters
        x = encoded_text[:, n:n+seq_len]
        
        # y is the target shifted over by 1
        y = np.zeros_like(x)
       
        #
        try:
            y[:, :-1] = x[:, 1:]
            y[:, -1]  = encoded_text[:, n+seq_len]
            
        # FOR POTENTIAL INDEXING ERROR AT THE END    
        except:
            y[:, :-1] = x[:, 1:]
            y[:, -1] = encoded_text[:, 0]
            
        yield x, y

In [43]:
sample_text = np.arange(20)

In [44]:
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5)

In [46]:
x, y = next(batch_generator)

In [47]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [48]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [49]:
class CharModel(nn.Module):
    
    def __init__(self, all_chars, num_hidden=256, num_layers=4,drop_prob=0.5,use_gpu=False):
        
        
        # SET UP ATTRIBUTES
        super().__init__()
        self.drop_prob = drop_prob
        self.num_layers = num_layers
        self.num_hidden = num_hidden
        self.use_gpu = use_gpu
        
        #CHARACTER SET, ENCODER, and DECODER
        self.all_chars = all_chars
        self.decoder = dict(enumerate(all_chars))
        self.encoder = {char: ind for ind,char in decoder.items()}
        
        
        self.lstm = nn.LSTM(len(self.all_chars), num_hidden, num_layers, dropout=drop_prob, batch_first=True)
        
        self.dropout = nn.Dropout(drop_prob)
        
        self.fc_linear = nn.Linear(num_hidden, len(self.all_chars))
      
    
    def forward(self, x, hidden):
                  
        
        lstm_output, hidden = self.lstm(x, hidden)
        
        
        drop_output = self.dropout(lstm_output)
        
        drop_output = drop_output.contiguous().view(-1, self.num_hidden)
        
        
        final_out = self.fc_linear(drop_output)
        
        
        return final_out, hidden
    
    
    def hidden_state(self, batch_size):
        '''
        Used as separate method to account for both GPU and CPU users.
        '''
        
        if self.use_gpu:
            
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda(),
                     torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda())
        else:
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden),
                     torch.zeros(self.num_layers,batch_size,self.num_hidden))
        
        return hidden


In [50]:
model = CharModel(
    all_chars=all_characters,
    num_hidden=512,
    num_layers=3,
    drop_prob=0.5,
    use_gpu=True,
)

In [51]:
total_param  = []
for p in model.parameters():
    total_param.append(int(p.numel()))

In [52]:
total_param

[172032,
 1048576,
 2048,
 2048,
 1048576,
 1048576,
 2048,
 2048,
 1048576,
 1048576,
 2048,
 2048,
 43008,
 84]

In [53]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
criterion = nn.CrossEntropyLoss()

In [54]:
train_percent = 0.1

In [55]:
train_ind = int(len(encoded_text)*train_percent)

In [56]:
train_data = encoded_text[:train_ind]

In [57]:
val_data = encoded_text[train_ind:]

In [58]:
len(train_data)

544560

In [59]:
len(val_data)

4901049

In [60]:
train_percent = 0.9

In [61]:
train_ind = int(len(encoded_text)*train_percent)

In [62]:
train_data = encoded_text[:train_ind]

In [63]:
val_data = encoded_text[train_ind:]

In [64]:
len(train_data)

4901048

In [65]:
len(val_data)

544561

In [66]:
epochs = 60
batch_size = 100
seq_len = 100
tracker = 0
num_char = max(encoded_text)+1


In [67]:
model.train()

CharModel(
  (lstm): LSTM(84, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc_linear): Linear(in_features=512, out_features=84, bias=True)
)

In [68]:
# Check to see if using GPU
if model.use_gpu:
    model.cuda()

for i in range(epochs):
    
    hidden = model.hidden_state(batch_size)
    
    
    for x,y in generate_batches(train_data,batch_size,seq_len):
        
        tracker += 1
        
        # One Hot Encode incoming data
        x = one_hot_encoder(x,num_char)
        
        # Convert Numpy Arrays to Tensor
        
        inputs = torch.from_numpy(x)
        targets = torch.from_numpy(y)
        
        # Adjust for GPU if necessary
        
        if model.use_gpu:
            
            inputs = inputs.cuda()
            targets = targets.cuda()
            
        # Reset Hidden State
        # If we dont' reset we would backpropagate through all training history
        hidden = tuple([state.data for state in hidden])
        
        model.zero_grad()
        
        lstm_output, hidden = model.forward(inputs,hidden)
        loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
        loss.backward()
        
        # POSSIBLE EXPLODING GRADIENT PROBLEM!
        # LET"S CLIP JUST IN CASE
        nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
        
        optimizer.step()
        
        
        
        ###################################
        ### CHECK ON VALIDATION SET ######
        #################################
        
        if tracker % 25 == 0:
            
            val_hidden = model.hidden_state(batch_size)
            val_losses = []
            model.eval()
            
            for x,y in generate_batches(val_data,batch_size,seq_len):
                
                # One Hot Encode incoming data
                x = one_hot_encoder(x,num_char)
                

                # Convert Numpy Arrays to Tensor

                inputs = torch.from_numpy(x)
                targets = torch.from_numpy(y)

                # Adjust for GPU if necessary

                if model.use_gpu:

                    inputs = inputs.cuda()
                    targets = targets.cuda()
                    
                # Reset Hidden State
                # If we dont' reset we would backpropagate through 
                # all training history
                val_hidden = tuple([state.data for state in val_hidden])
                
                lstm_output, val_hidden = model.forward(inputs,val_hidden)
                val_loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
                val_losses.append(val_loss.item())
            
            # Reset to training model after val for loop
            model.train()
            
            print(f"Epoch: {i} Step: {tracker} Val Loss: {val_loss.item()}")

Epoch: 0 Step: 25 Val Loss: 3.2024028301239014
Epoch: 0 Step: 50 Val Loss: 3.193345785140991
Epoch: 0 Step: 75 Val Loss: 3.189502477645874
Epoch: 0 Step: 100 Val Loss: 3.1815578937530518
Epoch: 0 Step: 125 Val Loss: 3.0615179538726807
Epoch: 0 Step: 150 Val Loss: 2.9390108585357666
Epoch: 0 Step: 175 Val Loss: 2.81571364402771
Epoch: 0 Step: 200 Val Loss: 2.688997983932495
Epoch: 0 Step: 225 Val Loss: 2.5762393474578857
Epoch: 0 Step: 250 Val Loss: 2.425086736679077
Epoch: 0 Step: 275 Val Loss: 2.310821294784546
Epoch: 0 Step: 300 Val Loss: 2.2313435077667236
Epoch: 0 Step: 325 Val Loss: 2.1682653427124023
Epoch: 0 Step: 350 Val Loss: 2.1150121688842773
Epoch: 0 Step: 375 Val Loss: 2.073878765106201
Epoch: 0 Step: 400 Val Loss: 2.0400619506835938
Epoch: 0 Step: 425 Val Loss: 2.0077548027038574
Epoch: 0 Step: 450 Val Loss: 1.9958865642547607
Epoch: 0 Step: 475 Val Loss: 1.9546757936477661
Epoch: 1 Step: 500 Val Loss: 1.9355239868164062
Epoch: 1 Step: 525 Val Loss: 1.910528302192688
Epoc

In [70]:
model_name = 'Hidden512_layers_3_shakes.net'

In [71]:
torch.save(model.state_dict(),model_name)

In [72]:
def predict_next_char(model,char,hidden=None,k=1):

  encoded_text = model.encoder[char]
  encoded_text = np.array([[encoded_text]])
  encoded_text = one_hot_encoder(encoded_text,len(model.all_chars))

  inputs = torch.from_numpy(encoded_text)

  if model.use_gpu:
    inputs = inputs.cuda()

  hidden = tuple([state.data for state in hidden])

  lstm_out,hidden = model(inputs,hidden)
  
  probs = F.softmax(lstm_out,dim=1).data

  if model.use_gpu:
    probs = probs.cpu()

  probs,index_positions = probs.topk(k)

  index_positions = index_positions_numpy().squeeze()

  probs = probs.numpy().flatten()

  probs = probs/probs.sum()

  char = np.random.choice(index_positions,p=probs)

  return model.decoder[char],hidden

In [73]:
model = CharModel(
    all_chars=all_characters,
    num_hidden=512,
    num_layers=3,
    drop_prob=0.5,
    use_gpu=True,
)

In [74]:
model.load_state_dict(torch.load(model_name))
model.eval()

CharModel(
  (lstm): LSTM(84, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc_linear): Linear(in_features=512, out_features=84, bias=True)
)

In [78]:
def predict_next_char(model, char, hidden=None, k=1):
        
        # Encode raw letters with model
        encoded_text = model.encoder[char]
        
        # set as numpy array for one hot encoding
        # NOTE THE [[ ]] dimensions!!
        encoded_text = np.array([[encoded_text]])
        
        # One hot encoding
        encoded_text = one_hot_encoder(encoded_text, len(model.all_chars))
        
        # Convert to Tensor
        inputs = torch.from_numpy(encoded_text)
        
        # Check for CPU
        if(model.use_gpu):
            inputs = inputs.cuda()
        
        
        # Grab hidden states
        hidden = tuple([state.data for state in hidden])
        
        
        # Run model and get predicted output
        lstm_out, hidden = model(inputs, hidden)

        
        # Convert lstm_out to probabilities
        probs = F.softmax(lstm_out, dim=1).data
        
        
        
        if(model.use_gpu):
            # move back to CPU to use with numpy
            probs = probs.cpu()
        
        
        # k determines how many characters to consider
        # for our probability choice.
        # https://pytorch.org/docs/stable/torch.html#torch.topk
        
        # Return k largest probabilities in tensor
        probs, index_positions = probs.topk(k)
        
        
        index_positions = index_positions.numpy().squeeze()
        
        # Create array of probabilities
        probs = probs.numpy().flatten()
        
        # Convert to probabilities per index
        probs = probs/probs.sum()
        
        # randomly choose a character based on probabilities
        char = np.random.choice(index_positions, p=probs)
       
        # return the encoded value of the predicted char and the hidden state
        return model.decoder[char], hidden

In [79]:
def generate_text(model, size, seed='The', k=1):
        
      
    
    # CHECK FOR GPU
    if(model.use_gpu):
        model.cuda()
    else:
        model.cpu()
    
    # Evaluation mode
    model.eval()
    
    # begin output from initial seed
    output_chars = [c for c in seed]
    
    # intiate hidden state
    hidden = model.hidden_state(1)
    
    # predict the next character for every character in seed
    for char in seed:
        char, hidden = predict_next_char(model, char, hidden, k=k)
    
    # add initial characters to output
    output_chars.append(char)
    
    # Now generate for size requested
    for i in range(size):
        
        # predict based off very last letter in output_chars
        char, hidden = predict_next_char(model, output_chars[-1], hidden, k=k)
        
        # add predicted character
        output_chars.append(char)
    
    # return string of predicted text
    return ''.join(output_chars)

In [80]:
print(generate_text(model, 1000, seed='The ', k=3))

The CONSTANCE OF WILLIAM
SHAKESPEARE IS COPYRIGHT 1990-1993 BY WORLD LIBRARY, INC., AND IS
PROVIDED BY PROJECT GUTENBERG ETEXT OF ILLINOIS BENEDICTINE COLLEGE
WITH PERMISSION.  ELECTRONIC AND MACHINE READABLE COPIES MAY BE
DISTRIBUTED SO LONG AS SUCH COPIES (1) ARE FOR YOUR OR OTHERS
PERSONILLALY OR YOUR OR OTHERS
PERSONAL USE ONLY, AND (2) ARE NOT DISTRIBUTION INCLUDES BY ANY BE
DISTRIBUTED SO LONG AS SUCH COPIES (1) ARE FOR YOUR OR OTHERS
PERSONAL USE ONLY, ARD (2) ARE FOR YOUR OR OTHERS
PERSONAL USE OLLY, AND (2) ARE NOT DISTRIBUTED OR USED
COMMERCIALLY.  PROHIBITED COMMERCIAL DISTRIBUTION INCLUDES BY ANY
SERVICE THAT CHARGES FOR DOWNLOAD TIME OR FOR MEMBERSHIP.>>


 ANT II. Some come to hear his sons.
  ANGELO, the Duke of Winchester. Though I was
    many merchant that stands to my carriage, where to be
    the child o' th' witch.
  CORIOLANUS. It is not a good fool. If there be such a fine
    That I was sold as I have sent me to me, I will see your
    mind.
  FIRST CITIZEN. The