<a href="https://colab.research.google.com/github/euguroglu/Machine-Learning-Projects/blob/master/Sklearn_Logistic_Regression_Basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing libraries

In [5]:
from sklearn.linear_model import LogisticRegression
import numpy as np

## Data Preperation

In [3]:
dataset = [[-2.0011, 0],
           [-1.4654, 0],
           [0.0965, 0],
           [1.3881, 0],
           [3.0641, 0],
           [7.6275, 1],
           [5.3324, 1],
           [6.9225, 1],
           [8.6754, 1],
           [7.6737, 1]]

In [4]:
dataset

[[-2.0011, 0],
 [-1.4654, 0],
 [0.0965, 0],
 [1.3881, 0],
 [3.0641, 0],
 [7.6275, 1],
 [5.3324, 1],
 [6.9225, 1],
 [8.6754, 1],
 [7.6737, 1]]

In [14]:
X = np.array(dataset)[:,0:1]
y = np.array(dataset)[:,1]

In [15]:
X

array([[-2.0011],
       [-1.4654],
       [ 0.0965],
       [ 1.3881],
       [ 3.0641],
       [ 7.6275],
       [ 5.3324],
       [ 6.9225],
       [ 8.6754],
       [ 7.6737]])

In [8]:
y

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

## Logistic Regression

In [11]:
model = LogisticRegression()

In [16]:
model.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Prediction

In [17]:
model.predict(X)

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [18]:
model.predict_proba(X)

array([[0.99853453, 0.00146547],
       [0.99740804, 0.00259196],
       [0.98643844, 0.01356156],
       [0.94830288, 0.05169712],
       [0.75430207, 0.24569793],
       [0.02307807, 0.97692193],
       [0.21456501, 0.78543499],
       [0.04771639, 0.95228361],
       [0.00766657, 0.99233343],
       [0.02199284, 0.97800716]])